using Xunit;using MiniCompiler.IR;using SemanticQueries.Core;using SemanticContracts;using Packages.BasicRange;using Packages.ArraySemantics;using Packages.BoundsBridge;using Packages.BoundsOptimizer;using Packages.LoopRange;using Packages.BranchSimplifier;using Packages.BranchProfile;using Packages.BranchLayout;using Baseline.DirectServices;
namespace SemanticQueries.Tests;
public class Tests
{
 static readonly ValueId I=new("i");static readonly ArrayId A=new("a");static readonly ProgramPoint P=new("body");
 static SemanticSession S(CompilationUnit u,StaticPlan p)=>new(p,u.Revision,()=>u.Revision);
 [Fact]public void Range_Constant_IsExact(){var u=new CompilationUnit().Constant(I,5);var r=S(u,new StaticPlan().Add(new BasicRangeProvider(u))).Query(new RangeQuery(),new RangeKey(I,P));Assert.Equal(new AbstractRange(5,5),r.Value);}
 [Fact]public void Range_MultipleSoundProviders_AreIntersected(){var u=new CompilationUnit();var p=new StaticPlan().Add<RangeKey,AbstractRange>(new ConstRange(new(0,100))).Add<RangeKey,AbstractRange>(new ConstRange(new(20,50)));var r=S(u,p).Query(new RangeQuery(),new RangeKey(I,P));Assert.Equal(new AbstractRange(20,50),r.Value);}
 [Fact]public void Range_DisjointProviders_Conflict(){var u=new CompilationUnit();var p=new StaticPlan().Add<RangeKey,AbstractRange>(new ConstRange(new(0,10))).Add<RangeKey,AbstractRange>(new ConstRange(new(20,30)));Assert.Equal(QueryStatus.Conflict,S(u,p).Query(new RangeQuery(),new RangeKey(I,P)).Status);}
 [Fact]public void Length_EqualProviders_Agree(){var u=new CompilationUnit();var p=new StaticPlan().Add<LengthKey,int>(new ConstLength(10)).Add<LengthKey,int>(new ConstLength(10));Assert.Equal(10,S(u,p).Query(new LengthQuery(),new(A,P)).Value);}
 [Fact]public void Length_DifferentProviders_Conflict(){var u=new CompilationUnit();var p=new StaticPlan().Add<LengthKey,int>(new ConstLength(10)).Add<LengthKey,int>(new ConstLength(11));Assert.Equal(QueryStatus.Conflict,S(u,p).Query(new LengthQuery(),new(A,P)).Status);}
 [Fact]public void InBounds_RangeAndLength_ProvesAccess(){var u=new CompilationUnit().Constant(I,3).Array(A,10);var p=new StaticPlan().Add(new BasicRangeProvider(u)).Add(new ArrayLengthProvider(u)).Add(new BoundsBridgeProvider());Assert.Equal(QueryStatus.Known,S(u,p).Query(new InBoundsQuery(),new(A,I,P)).Status);}
 [Fact]public void BoundsOptimizer_KeepsUnknownCheck(){var u=new CompilationUnit().Array(A,10);var p=new StaticPlan().Add(new ArrayLengthProvider(u)).Add(new BoundsBridgeProvider());Assert.False(new BoundsCheckOptimizer().Run(new(A,I,P),S(u,p)).Removed);}
 [Fact]public void BetterRangeProvider_ImprovesExistingBoundsOptimizer(){var u=new CompilationUnit().Array(A,10).Loop(new(I,0,10,P));var basic=new StaticPlan().Add(new BasicRangeProvider(u)).Add(new ArrayLengthProvider(u)).Add(new BoundsBridgeProvider());var better=new StaticPlan().Add(new BasicRangeProvider(u)).Add(new LoopRangeProvider(u)).Add(new ArrayLengthProvider(u)).Add(new BoundsBridgeProvider());var opt=new BoundsCheckOptimizer();Assert.False(opt.Run(new(A,I,P),S(u,basic)).Removed);Assert.True(opt.Run(new(A,I,P),S(u,better)).Removed);}
 [Fact]public void BetterRangeProvider_AlsoImprovesBranchSimplifier(){var u=new CompilationUnit().Loop(new(I,0,10,P));var p=new StaticPlan().Add(new LoopRangeProvider(u));Assert.True(new BranchSimplificationPass().IsAlwaysTrue(new(I,10,P),S(u,p)));}
 [Fact]public void ProviderRegistrationOrder_DoesNotChangeResult(){var u=new CompilationUnit().Array(A,10).Loop(new(I,0,10,P));StaticPlan P1()=>new StaticPlan().Add(new LoopRangeProvider(u)).Add(new ArrayLengthProvider(u)).Add(new BoundsBridgeProvider());StaticPlan P2()=>new StaticPlan().Add(new BoundsBridgeProvider()).Add(new ArrayLengthProvider(u)).Add(new LoopRangeProvider(u));var q=new InBoundsQuery();Assert.Equal(S(u,P1()).Query(q,new(A,I,P)),S(u,P2()).Query(q,new(A,I,P)));}
 [Fact]public void SemanticSession_MemoizesRepeatedQuery(){var u=new CompilationUnit().Constant(I,5);var provider=new BasicRangeProvider(u);var s=S(u,new StaticPlan().Add(provider));for(var x=0;x<100;x++)s.Query(new RangeQuery(),new RangeKey(I,P));Assert.Equal(1,provider.Calls);}
 [Fact]public void OldSemanticSession_CannotServeNewRevision(){var u=new CompilationUnit().Constant(I,5);var s=S(u,new StaticPlan().Add(new BasicRangeProvider(u)));_ = s.Query(new RangeQuery(),new RangeKey(I,P));u.MutateConstant(I,100);Assert.Throws<StaleSemanticSessionException>(()=>s.Query(new RangeQuery(),new RangeKey(I,P)));}
 [Fact]public void QueryCycle_IsDetected(){var u=new CompilationUnit();var a=new CycleA();var b=new CycleB();a.B=b;b.A=a;var p=new StaticPlan().Add<string,int>(a).Add<string,int>(b);Assert.Throws<QueryCycleException>(()=>S(u,p).Query(a,"x"));}
 [Fact]public void Probability_ReordersBranchLayout(){var b=new BranchId("b");var u=new CompilationUnit().ProfileBranch(b,.05);var p=new StaticPlan().Add(new ProfileBranchProbabilityProvider(u));Assert.Equal(new[]{"hot","cold"},new BranchLayoutPass().Order(new(b,"cold","hot"),S(u,p)));}
 [Fact]public void Probability_DoesNotRemoveBoundsCheck(){var b=new BranchId("b");var u=new CompilationUnit().Array(A,10).ProfileBranch(b,.999999);var p=new StaticPlan().Add(new ProfileBranchProbabilityProvider(u)).Add(new ArrayLengthProvider(u)).Add(new BoundsBridgeProvider());Assert.False(new BoundsCheckOptimizer().Run(new(A,I,P),S(u,p)).Removed);}
 [Fact]public void MalformedProbability_IsRejected(){var u=new CompilationUnit();var p=new StaticPlan().Add<BranchId,double>(new BadProbability());Assert.Throws<QueryContractException>(()=>S(u,p).Query(new BranchProbabilityQuery(),new BranchId("b")));}
 [Fact]public void ConventionalBaseline_AlsoAcceptsIndependentLoopRange(){var u=new CompilationUnit().Array(A,10).Loop(new(I,0,10,P));var basic=new BaselineBoundsService(new([new BasicRangeService(u)]),new ArrayLengthService(u));var extended=new BaselineBoundsService(new([new BasicRangeService(u),new LoopRangeService(u)]),new ArrayLengthService(u));var k=new InBoundsKey(A,I,P);Assert.False(basic.InBounds(k));Assert.True(extended.InBounds(k));}
 public sealed class ConstRange(AbstractRange r):IQueryProvider<RangeKey,AbstractRange>{public QueryResult<AbstractRange> TryGet(RangeKey k,QueryContext c)=>QueryResult<AbstractRange>.Known(r);}public sealed class ConstLength(int n):IQueryProvider<LengthKey,int>{public QueryResult<int> TryGet(LengthKey k,QueryContext c)=>QueryResult<int>.Known(n);}public sealed class BadProbability:IQueryProvider<BranchId,double>{public QueryResult<double> TryGet(BranchId k,QueryContext c)=>QueryResult<double>.Known(2.4);}
 public sealed class CycleA:IQuerySpec<string,int>,IQueryProvider<string,int>{public CycleB? B;public string Name=>"A";public QueryResult<int> Combine(IReadOnlyList<int> v)=>v.Count==0?QueryResult<int>.Unknown:QueryResult<int>.Known(v[0]);public QueryResult<int> TryGet(string k,QueryContext c)=>c.Query(B!,k);}public sealed class CycleB:IQuerySpec<string,int>,IQueryProvider<string,int>{public CycleA? A;public string Name=>"B";public QueryResult<int> Combine(IReadOnlyList<int> v)=>v.Count==0?QueryResult<int>.Unknown:QueryResult<int>.Known(v[0]);public QueryResult<int> TryGet(string k,QueryContext c)=>c.Query(A!,k);}
}
